### ISSUE TITLE
PNG file may not have P3 / P6 header

### ISSUE THREAD

**Issue by kunalbarchha** [pjmlp/ppm2png#2]
https://github.com/pjmlp/ppm2png/blob/f36153b9dc574ab3312416214c39793eb7e74e2c/java/src/main/java/org/progtools/ppm2png/PPM2PNG.java#L53

I am trying to use your logic in one of my requirement to convert PNG to PPM, and the program failes at line 53 of your code. Because PNG doesn't have P3 header.

**Comment by pjmlp** [comment]
That is to be expected, this tool is only thought out to convert a specific PPM format into PNGs, the reverse is not supported and never will.
